CreateUsersTable: create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreateFacultiesTable: create table `faculties` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateCareersTable: create table `careers` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `faculty_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateCareersTable: alter table `careers` add constraint `careers_faculty_id_foreign` foreign key (`faculty_id`) references `faculties` (`id`)
CreateStudentsTable: create table `students` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `lastName` varchar(255) not null, `level` int not null, `fone` int not null, `rut` int not null, `verificatorDigit` varchar(255) not null, `address` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateStudentCareerTable: create table `student_career` (`id` bigint unsigned not null auto_increment primary key, `career_id` bigint unsigned not null, `student_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateSubjectsTable: create table `subjects` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `name` varchar(255) not null, `referenceCoordination` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateRequirementsTable: create table `requirements` (`id` bigint unsigned not null auto_increment primary key, `subject_id` bigint unsigned not null, `referenceSubject` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateRequirementsTable: alter table `requirements` add constraint `requirements_subject_id_foreign` foreign key (`subject_id`) references `subjects` (`id`)
CreatePostulationsTable: create table `postulations` (`id` bigint unsigned not null auto_increment primary key, `numberTime` int not null, `referenceTeacher` int not null, `accepted` int not null, `subject_id` bigint unsigned not null, `student_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePostulationsTable: alter table `postulations` add constraint `postulations_subject_id_foreign` foreign key (`subject_id`) references `subjects` (`id`)
CreatePostulationsTable: alter table `postulations` add constraint `postulations_student_id_foreign` foreign key (`student_id`) references `students` (`id`)
CreateStudentScoresTable: create table `student_scores` (`id` bigint unsigned not null auto_increment primary key, `score` int not null, `postulation_id` bigint unsigned not null, `student_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateStudentScoresTable: alter table `student_scores` add constraint `student_scores_postulation_id_foreign` foreign key (`postulation_id`) references `postulations` (`id`)
CreateStudentScoresTable: alter table `student_scores` add constraint `student_scores_student_id_foreign` foreign key (`student_id`) references `students` (`id`)
